export const FETCH_TEAMS = "FETCH_TEAMS";

export const FETCH_TEAMS_SUCCESS= "FETCH_TEAMS_SUCCESS";
export const FETCH_TEAMS_REQUEST="FETCH_TEAMS_REQUEST";
export const FETCH_TEAMS_FAIL="FETCH_TEAMS_FAIL";

export const FETCH_TEAM_SUCCESS= "FETCH_TEAM_SUCCESS";
export const FETCH_TEAM_REQUEST="FETCH_TEAM_REQUEST";
export const FETCH_TEAM_FAIL="FETCH_TEAM_FAIL";

export const FETCH_TEAMNAME_SUCCESS= "FETCH_TEAMNAME_SUCCESS";
export const FETCH_TEAMNAME_REQUEST="FETCH_TEAMNAME_REQUEST";
export const FETCH_TEAMNAME_FAIL="FETCH_TEAMNAME_FAIL";

export const CHANGE_THEME= "CHANGE_THEME";